{{- if .Values.githubConfig }}
{{- if and .Values.githubConfig.enabled (not .Values.githubConfig.accountPasswordsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "spinnaker.fullname" . }}-github-account-passwords
  labels:
    {{- include "spinnaker.standard-labels" . | nindent 4 }}
    component: clouddriver
type: Opaque
data:
  {{- range $index, $account := .Values.githubConfig.accounts }}
  {{- if and $account.token $account.password }}
    {{ printf ".githubConfig.accounts.%s can not have both a token and passord." $account.name | fail }}
  {{- else if not (or $account.token $account.password) }}
    {{ printf ".githubConfig.accounts.%s must have a token or passord." $account.name | fail }}
  {{- end }}
  {{- $githubAccountPassword := printf "%s:%s" $account.username $account.password }}
  {{ $account.name }}: {{ $account.token | default $githubAccountPassword | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
